Repository codesquad-member-2020/todo-4, pull requests merged in 2020-04, with the labels that each got.

#11 [FE] 기본 환경 설정 구성
  web/.babelrc
  web/.gitignore
  web/.storybook/config.js
  web/.storybook/main.js
  web/package-lock.json
  web/package.json
  web/scss.d.ts
  web/src/component/AddingCard/AddingCard.scss
  web/src/component/AddingCard/index.ts
  web/src/component/Card/card.scss
  web/src/component/Card/index.ts
  web/src/component/Header/Header.scss
  web/src/component/Header/index.ts
  web/src/component/Table/Table.scss
  web/src/component/Table/index.ts
  web/src/component/customButton/CustomButton.scss
  web/src/component/customButton/index.ts
  web/src/stories/AddingCard.stories.ts
  web/src/stories/Card.stories.ts
  web/src/stories/Header.stories.ts
  web/src/stories/InlineList.stories.ts
  web/src/stories/Spacing.stories.ts
  web/src/stories/Table.stories.ts
  web/src/stories/customButton.stories.ts
  web/src/styled-component/InlineList/InlineList.scss
  web/src/styled-component/InlineList/index.ts
  web/src/styled-component/Spacing/Spacing.scss
  web/src/styled-component/Spacing/index.ts
  web/src/util/color.ts
  web/src/util/style/reset.scss
  web/src/util/style/semantic-ui/icon.css
  web/src/util/style/semantic-ui/themes/default/assets/fonts/brand-icons.eot
  web/src/util/style/semantic-ui/themes/default/assets/fonts/brand-icons.svg
  web/src/util/style/semantic-ui/themes/default/assets/fonts/brand-icons.ttf
  web/src/util/style/semantic-ui/themes/default/assets/fonts/brand-icons.woff
  web/src/util/style/semantic-ui/themes/default/assets/fonts/brand-icons.woff2
  web/src/util/style/semantic-ui/themes/default/assets/fonts/icons.eot
  web/src/util/style/semantic-ui/themes/default/assets/fonts/icons.otf
  web/src/util/style/semantic-ui/themes/default/assets/fonts/icons.svg
  web/src/util/style/semantic-ui/themes/default/assets/fonts/icons.ttf
  web/src/util/style/semantic-ui/themes/default/assets/fonts/icons.woff
  web/src/util/style/semantic-ui/themes/default/assets/fonts/icons.woff2
  web/src/util/style/semantic-ui/themes/default/assets/fonts/outline-icons.eot
  web/src/util/style/semantic-ui/themes/default/assets/fonts/outline-icons.svg
  web/src/util/style/semantic-ui/themes/default/assets/fonts/outline-icons.ttf
  web/src/util/style/semantic-ui/themes/default/assets/fonts/outline-icons.woff
  web/src/util/style/semantic-ui/themes/default/assets/fonts/outline-icons.woff2
  web/src/util/style/semantic-ui/themes/default/assets/images/flags.png
  web/tsconfig.json
  web/webpack.config.js
Labels: enhancement

#18 [iOS] Todo List Board UI 구현
  mobile/.gitignore
  mobile/README.md
  mobile/TodoList/TodoList.xcodeproj/project.pbxproj
  mobile/TodoList/TodoList.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  mobile/TodoList/TodoList.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  mobile/TodoList/TodoList/AppDelegate.swift
  mobile/TodoList/TodoList/Assets.xcassets/AppIcon.appiconset/Contents.json
  mobile/TodoList/TodoList/Assets.xcassets/Contents.json
  mobile/TodoList/TodoList/Base.lproj/LaunchScreen.storyboard
  mobile/TodoList/TodoList/Base.lproj/Main.storyboard
  mobile/TodoList/TodoList/Controllers/BoardViewController.swift
  mobile/TodoList/TodoList/Controllers/CardListViewController.swift
  mobile/TodoList/TodoList/DataSources/CardListDataSource.swift
  mobile/TodoList/TodoList/Info.plist
  mobile/TodoList/TodoList/Models/BoardResponse.swift
  mobile/TodoList/TodoList/Models/Observers.swift
  mobile/TodoList/TodoList/Networking/APIRouter.swift
  mobile/TodoList/TodoList/Networking/Endpoints.swift
  mobile/TodoList/TodoList/Networking/NetworkManager.swift
  mobile/TodoList/TodoList/NetworkingTests/MockJSON.swift
  mobile/TodoList/TodoList/NetworkingTests/URLProtocolMock.swift
  mobile/TodoList/TodoList/SceneDelegate.swift
  mobile/TodoList/TodoList/Utils/ReusableView.swift
  mobile/TodoList/TodoList/Utils/UILoader.swift
  mobile/TodoList/TodoList/ViewModels/CardListViewModel.swift
  mobile/TodoList/TodoList/Views/CardCell.swift
  mobile/TodoList/TodoList/Views/CardCountView.swift
  mobile/TodoList/TodoListTests/CardListViewModelTests.swift
  mobile/TodoList/TodoListTests/Info.plist
  mobile/result1.png
Labels: enhancement, refactor

#16 [FE] 컴포넌트 이벤트 작성
  web/package-lock.json
  web/package.json
  web/src/component/AddingCard/index.ts
  web/src/component/Board/index.ts
  web/src/component/Card/index.ts
  web/src/component/Modal/Modal.scss
  web/src/component/Modal/index.ts
  web/src/component/Table/AddingCard/AddingCard.scss
  web/src/component/Table/AddingCard/index.ts
  web/src/component/Table/Card/EditModal/EditModal.scss
  web/src/component/Table/Card/EditModal/index.ts
  web/src/component/Table/Card/card.scss
  web/src/component/Table/Card/index.ts
  web/src/component/Table/Table.scss
  web/src/component/Table/TableHeader/index.ts
  web/src/component/Table/index.ts
  web/src/component/customButton/CustomButton.scss
  web/src/index.scss
  web/src/index.ts
  web/src/stories/AddingCard.stories.ts
  web/src/stories/Board.stories.ts
  web/src/stories/Card.stories.ts
  web/src/stories/EditModal.stories.ts
  web/src/stories/Table.stories.ts
  web/src/styled-component/InlineList/InlineList.scss
  web/src/styled-component/InlineList/index.ts
  web/webpack.config.js
Labels: enhancement, fe리뷰요청

#28 [iOS] 새로운 카드 추가 기능 구현
  mobile/README.md
  mobile/TodoList/TodoList.xcodeproj/project.pbxproj
  mobile/TodoList/TodoList/AppDelegate.swift
  mobile/TodoList/TodoList/Base.lproj/Main.storyboard
  mobile/TodoList/TodoList/Controllers/BoardViewController.swift
  mobile/TodoList/TodoList/Controllers/CardListViewController.swift
  mobile/TodoList/TodoList/Controllers/FormViewController.swift
  mobile/TodoList/TodoList/Models/BoardResponse.swift
  mobile/TodoList/TodoList/Models/CardIDResponse.swift
  mobile/TodoList/TodoList/Models/Observers.swift
  mobile/TodoList/TodoList/Networking/APIRouter.swift
  mobile/TodoList/TodoList/Networking/Endpoints.swift
  mobile/TodoList/TodoList/Networking/NetworkManager.swift
  mobile/TodoList/TodoList/NetworkingTests/JSONMocks/BoardResponse.json
  mobile/TodoList/TodoList/NetworkingTests/JSONMocks/NewCardResponse.json
  mobile/TodoList/TodoList/NetworkingTests/MockJSON.swift
  mobile/TodoList/TodoList/NetworkingTests/URLProtocolMock.swift
  mobile/TodoList/TodoList/SceneDelegate.swift
  mobile/TodoList/TodoList/Utils/FirstResponder.swift
  mobile/TodoList/TodoList/Utils/ReusableView.swift
  mobile/TodoList/TodoList/ViewModels/CardListViewModel.swift
  mobile/TodoList/TodoListTests/CardListViewModelTests.swift
  mobile/result2.png
Labels: enhancement, refactor

#35 [FE] 데이터 연결을 위한 준비
  web/package-lock.json
  web/package.json
  web/scss.d.ts
  web/src/component/Board/index.ts
  web/src/component/Header/Header.scss
  web/src/component/Header/LogColumn/LogColumn.scss
  web/src/component/Header/LogColumn/LogColumnCard/LogColumnCard.scss
  web/src/component/Header/LogColumn/LogColumnCard/index.ts
  web/src/component/Header/LogColumn/LogColumnCard/yein.jpg
  web/src/component/Header/LogColumn/index.ts
  web/src/component/Header/index.ts
  web/src/component/Modal/index.ts
  web/src/component/Spinner/Spinner.scss
  web/src/component/Spinner/index.ts
  web/src/component/Table/AddingCard/index.ts
  web/src/component/Table/Card/EditModal/EditModal.scss
  web/src/component/Table/Card/EditModal/index.ts
  web/src/component/Table/Card/FailModal/FailModal.scss
  web/src/component/Table/Card/FailModal/index.ts
  web/src/component/Table/Card/card.scss
  web/src/component/Table/Card/index.ts
  web/src/component/Table/Table.scss
  web/src/component/Table/TableHeader/index.ts
  web/src/component/Table/index.ts
  web/src/index.ts
  web/src/stories/AddingCard.stories.ts
  web/src/stories/Board.stories.ts
  web/src/stories/Card.stories.ts
  web/src/stories/EditModal.stories.ts
  web/src/stories/FailModal.stories.ts
  web/src/stories/Header.stories.ts
  web/src/stories/InlineList.stories.ts
  web/src/stories/LogColumn.stories.ts
  web/src/stories/LogColumnCard.stories.ts
  web/src/stories/Spinner.stories.ts
  web/src/stories/Table.stories.ts
  web/src/styled-component/InlineList/InlineList.scss
  web/src/styled-component/InlineList/index.ts
Labels: enhancement, fe리뷰요청

#48 [iOS] 할 일 카드 삭제 및 이동 구현, Activities 화면 구현
  mobile/README.md
  mobile/TodoList/TodoList.xcodeproj/project.pbxproj
  mobile/TodoList/TodoList/Base.lproj/Main.storyboard
  mobile/TodoList/TodoList/Controllers/ActivitiesViewController.swift
  mobile/TodoList/TodoList/Controllers/BoardViewController.swift
  mobile/TodoList/TodoList/Controllers/CardListViewController.swift
  mobile/TodoList/TodoList/Controllers/FormViewController.swift
  mobile/TodoList/TodoList/DataSources/CardListDataSource.swift
  mobile/TodoList/TodoList/Delegates/CardListDelegate.swift
  mobile/TodoList/TodoList/Models/ActivitiesResponse.swift
  mobile/TodoList/TodoList/Models/BoardResponse.swift
  mobile/TodoList/TodoList/Models/CardIDResponse.swift
  mobile/TodoList/TodoList/Models/CardRequest.swift
  mobile/TodoList/TodoList/Models/FloatingCard.swift
  mobile/TodoList/TodoList/Networking/APIRouter.swift
  mobile/TodoList/TodoList/Networking/Endpoints.swift
  mobile/TodoList/TodoList/Networking/NetworkManager.swift
  mobile/TodoList/TodoList/NetworkingTests/URLProtocolMock.swift
  mobile/TodoList/TodoList/Utils/DateFormatterExtensions.swift
  mobile/TodoList/TodoList/Utils/DragDrop.swift
  mobile/TodoList/TodoList/ViewModels/CardListViewModel.swift
  mobile/TodoList/TodoList/Views/CardCell.swift
  mobile/result3.png
Labels: enhancement
